server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

spring:
  messages:
    basename: lang/res
  mvc:
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui-custom.html'

mongodb:
  host: localhost
  uri=: mongodb://root:root@localhost:27017/?authSource=pets
  database: pets
  authenticationDatabase: admin
  authSource: admin
  username: root
  password: root
  port: 27017