version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - ~/data/db1:/data/db
    networks:
      - mongors-network
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip", "localhost,mongo1", "--replSet", "myReplicaSet" ]
  mongo2:
    container_name: mongo2
    image: mongo
    volumes:
      - ~/data/db2:/data/db
    networks:
      - mongors-network
    ports:
      - 27018:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip", "localhost,mongo2",  "--replSet", "myReplicaSet" ]
  mongo3:
    container_name: mongo3
    image: mongo
    volumes:
      - ~/data/db3:/data/db
    networks:
      - mongors-network
    ports:
      - 27019:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip", "localhost,mongo3", "--replSet", "myReplicaSet" ]
  mongoinit:
    image: mongo
    restart: "no"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./initiate_replica_set.sh:/initiate_replica_set.sh
    entrypoint: 
      - /initiate_replica_set.sh
    networks:
      - mongors-network
networks:
  mongors-network:
    driver: bridge